let comandoCor = document.getElementById("cor"); // FOI CRIADO UMA VARIAVEL PUXANDOO O "ID COR"

document.getElementById("gerar").onclick = function() { // AQUI EXECUTARA UMA FUNÇÃO AO CLICAR AONDE TEM O ID GERA NO HTML
    let corAleatoria = "#" + Math.floor(Math.random() * 16777215).toString(16) // ESSE RANDOM VAI GERA UM NUMERO ALEATORIO ENTRE 0 E 1 E ELE É MULTIPLICADO POR 16777215 MAIOR NUMERO HEXADECIMAL POSSIVEL O FLOOR VAI AREDONDAR ESSE NUMERO PARA BAIXO PARA ELE FICAR ENTEIRO E ELE TA SENDO USADO PELO ID COR AONDE APARECE O NUMERO GERADO COM ESSE TOSTRING 16 ELE É CONVERTIDO NA BASE 16 QUE É HEXADECIMA E ADICIONOU MAIS O HASTAG 
    comandoCor.textContent = corAleatoria; // ESSE NUMERO ALEATORIA VAI PARA DENTRO DO BOTÃO
    document.body.style.backgroundColor = corAleatoria // AQUI EU TO CHAMANDO UM COMANDO DE BACKGROUNDCOLOR E ESSE NUMERO ALEATORIO GERADO VAI SER O NUMERO QUE REPRESENTA UMA COR
};